# Site
name: "Djoser Genomics"
title: "Djoser Genomics"
description: "Djoser Genomics: Exploring Bioinformatics, One Step at a Time"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl: ""
google_analytics: "G-QN6Q5EFQGR"
include: ["_pages"]
permalink: /:title/

authors:
  Nourelden:
    name: Nourelden Rihan
    display_name: Nourelden Rihan
    email: noureldenrihan@gmail.com
    web: https://nourelden-rihan.web.app
    description: "Creator of Djoser Genomics"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, README.md, Gemfile, Gemfile.lock]
